/*
 * wml-runtime.js
 * Generated by wmlc — the WML compiler.
 * Powers STATE, BIND, REPEAT, IF/ELSE and wml-bind without any
 * hand-written script in the source .wml file.
 */
(function () {
  'use strict';

  var stateEl = document.getElementById('wml-state');
  var state = stateEl ? JSON.parse(stateEl.textContent) : {};
  var subscribers = {}; // stateName -> [fn(newValue)]

  function subscribe(name, fn) {
    (subscribers[name] = subscribers[name] || []).push(fn);
  }

  function coerce(kind, raw) {
    if (kind === 'number') return Number(raw);
    if (kind === 'boolean') return raw === 'true' || raw === true;
    if (kind === 'list') return typeof raw === 'string' ? raw.split(',').map(function (s) { return s.trim(); }) : raw;
    return raw;
  }

  function setState(name, value) {
    state[name] = value;
    (subscribers[name] || []).forEach(function (fn) { fn(value); });
  }

  function getState(name) {
    return state[name];
  }

  var ACTIONS = {
    set: function (name, arg) { setState(name, arg); },
    increment: function (name) { setState(name, (Number(state[name]) || 0) + 1); },
    decrement: function (name) { setState(name, (Number(state[name]) || 0) - 1); },
    toggle: function (name) { setState(name, !state[name]); },
    append: function (name, arg) {
      var list = Array.isArray(state[name]) ? state[name].slice() : [];
      list.push(arg);
      setState(name, list);
    },
    clear: function (name) { setState(name, Array.isArray(state[name]) ? [] : ''); }
  };

  function initBindText() {
    document.querySelectorAll('[data-wml-bind]').forEach(function (el) {
      var name = el.getAttribute('data-wml-bind');
      var apply = function (val) {
        if ('value' in el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA')) {
          if (el.type === 'checkbox') el.checked = !!val;
          else el.value = val;
        } else {
          el.textContent = val;
        }
      };
      apply(state[name]);
      subscribe(name, apply);
    });
  }

  function initEvents() {
    document.querySelectorAll('[data-wml-bind-events]').forEach(function (el) {
      var directives;
      try { directives = JSON.parse(el.getAttribute('data-wml-bind-events')); }
      catch (e) { return; }
      directives.forEach(function (d) {
        el.addEventListener(d.event, function () {
          var fn = ACTIONS[d.action];
          if (fn) fn(d.state, d.value);
        });
      });
    });
  }

  function initConditionals() {
    document.querySelectorAll('[data-wml-if]').forEach(function (el) {
      var name = el.getAttribute('data-wml-if');
      var negate = el.hasAttribute('data-wml-else');
      var placeholder = document.createComment('wml-if:' + name);
      el.parentNode.insertBefore(placeholder, el);
      var mounted = true;
      var render = function (val) {
        var show = negate ? !val : !!val;
        if (show && !mounted) {
          placeholder.parentNode.insertBefore(el, placeholder.nextSibling);
          mounted = true;
        } else if (!show && mounted) {
          el.remove();
          mounted = false;
        }
      };
      render(state[name]);
      subscribe(name, render);
    });
  }

  function initRepeats() {
    document.querySelectorAll('template[data-wml-repeat]').forEach(function (tmpl) {
      var source = tmpl.getAttribute('data-wml-repeat');
      var asVar = tmpl.getAttribute('data-wml-as');
      var container = document.createElement('span');
      container.setAttribute('data-wml-repeat-output', source);
      tmpl.parentNode.insertBefore(container, tmpl.nextSibling);

      var render = function (list) {
        container.innerHTML = '';
        (list || []).forEach(function (item) {
          var html = tmpl.innerHTML.split('{{' + asVar + '}}').join(item);
          var wrapper = document.createElement('span');
          wrapper.innerHTML = html;
          while (wrapper.firstChild) container.appendChild(wrapper.firstChild);
        });
      };
      render(state[source]);
      subscribe(source, render);
    });
  }

  document.addEventListener('DOMContentLoaded', function () {
    initBindText();
    initConditionals();
    initRepeats();
    initEvents();
  });

  window.WML = { getState: getState, setState: setState, subscribe: subscribe };
})();